config/routes.rb
Rails.application.routes.draw do
  get 'quiz_results/new'

  get 'quizzes/new'

  get 'user_milestones/new'

  get 'sections/new'

  get 'chapters/new'

  get 'courses/new'

  get 'organizations/new'

  get 'sessions/new'

  resources :organizations
  resources :users
  resources :courses do
    post 'save'=> 'courses#save'
    get 'createTempChapter'=> 'chapters#createTempChapter'
  end

  resources :chapters do
    post 'save'=> 'chapters#save'
  end
  resources :sections do
    post 'saveVideo'=> 'sections#saveVideo'
  end
  resources :quizzes
  resources :quizzes do
    resources :quiz_results
  end

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'organizations#new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'addUsers' => 'organizations#newUsers'
  get 'editMode' => 'courses#editMode'
  get 'createTempCourse'=> 'courses#createTempCourse'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
  end

  def show
    @quiz = Quiz.find(params[:id])
    @questions = QuizQuestion.all.find_all{|question| question.quiz_id==@quiz.id}
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/new.html.erb
<h1>Quizzes#new</h1>
<p>Find me in app/views/quizzes/new.html.erb</p>

app/views/quizzes/show.html.erb
<div class="container">
<h2>Chapter <%= @quiz.chapter_id%> Quiz</h2>

  <div class="row">


    <%= form_tag new_quiz_quiz_result_url(@quiz), :method => 'get' do %>
  <ol>
    <% @questions.each do |question| %>

            <div class ="input-field col s12" style="margin-top:2em" >
              <li style="font-size: 22px"><%= question.question %></li>
              <% if !question.imgSource.nil?%>
                  <img class="materialboxed" height="400px" src=<%= asset_path question.imgSource %>>
              <%end%>
            </div>
            <div class ="input-field col s12" style="">
            <%= radio_button_tag question.id,'a'%>
              <%= label_tag question.id.to_s+'_a', question.answer_choices.find_by(letter:"a").answer %>

            </div>
            <div class ="input-field col s12" >
              <%= radio_button_tag question.id,'b'%>
              <%= label_tag question.id.to_s+'_b', question.answer_choices.find_by(letter:"b").answer %>
            </div>
            <div class ="input-field col s12">
              <%= radio_button_tag question.id,'c'%>
              <%= label_tag question.id.to_s+'_c', question.answer_choices.find_by(letter:"c").answer %>
            </div>
            <div class ="input-field col s12" >
              <%= radio_button_tag question.id,'d'%>
              <%= label_tag question.id.to_s+'_d', question.answer_choices.find_by(letter:"d").answer %>
            </div>
    <% end %>
    <div class="col s3 offset-s9">
        <%= submit_tag "Done",:class => "btn" %>
    </div>
</ol>

    <% end %>


  </div>
</div>