config/routes.rb
Rails.application.routes.draw do
  get 'quiz_results/new'

  get 'quizzes/new'

  get 'user_milestones/new'

  get 'sections/new'

  get 'chapters/new'

  get 'courses/new'

  get 'organizations/new'

  get 'sessions/new'

  resources :organizations
  resources :users
  resources :courses do
    post 'save'=> 'courses#save'
    get 'createTempChapter'=> 'chapters#createTempChapter'
  end

  resources :chapters do
    post 'save'=> 'chapters#save'
  end
  resources :sections do
    post 'saveVideo'=> 'sections#saveVideo'
  end
  resources :quizzes
  resources :quizzes do
    resources :quiz_results
  end

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'organizations#new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'addUsers' => 'organizations#newUsers'
  get 'editMode' => 'courses#editMode'
  get 'createTempCourse'=> 'courses#createTempCourse'

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def new
  end

  def show
    @section = Section.find(params[:id])
    @video = youtube_embed(@section.content)
    @sections = @section.chapter.sections
    @quizzes = Quiz.all
  end

  def edit
    @section = Section.find(params[:id])
    @video = youtube_embed(@section.content)
    @sections = @section.chapter.sections
    @quizzes = Quiz.all
  end

  def saveVideo
    vidURL = params[:vidURL]
    section = Section.find(params[:section_id])
    section.content  = vidURL
    section.save
    redirect_to section
  end
  private

  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end
    "https://www.youtube.com/embed/#{ youtube_id }"
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/edit.html.erb
<h2 style="margin-bottom: 0px"><%= @section.name %></h2>
<div class="container">
  <%= form_tag section_saveVideo_path(@section.id) do %>
      <h5 class="center" style="margin-bottom: 10px; margin-top: 10px;">
       <%= button_tag(:class => "orange btn-medium btn-floating ") do %>
          <i class="mdi-content-save"></i>
      <% end %>
     </h5>
      <%= text_field_tag "vidURL", @section.content %>
      <% end %>
</div>
<div class="valign-wrapper">

  <% if @sections.find_by(order: @section.order-1) %>
      <%= link_to @sections.find_by(order: @section.order-1), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-back valign"></i>
      <% end %>
  <% else %>
      <div class="btn btn-default disabled">
        <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-back valign"></i>
      </div>
  <% end %>

  <div class="container">
    <% if @section.contentType =="vid" %>
        <div class="video-container">
          <iframe width="854" height="510" src="<%=raw(@video)%>" frameborder="0" allowfullscreen></iframe>
        </div>
    <% end %>
  </div>

  <% if @sections.find_by(order: @section.order+1) %>
      <%= link_to @sections.find_by(order: @section.order+1), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-forward valign"></i>
      <% end %>
  <% else %>
      <%= link_to @quizzes.find_by(chapter_id: @section.chapter_id), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-forward valign"></i>
      <% end %>
  <% end %>
</div>
<div class="container">
  <h3 class="left-align"><a style="color:<%if passed?(@section.chapter)==1%> green"
                            <% elsif passed?(@section.chapter)==0 %>red"
  <% else %>grey"
  <% end %>href="<%= polymorphic_path @section.chapter.course %>
  "><i class="mdi-navigation-chevron-left"> </i><%= @section.chapter.name %> </a></h3>
</div>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h2 <% if current_user.clearance>1%>style="margin-bottom: 0px"<%end%>><%= @section.name %></h2>
<div class = "container">
  <% if current_user.clearance>1%>
<h5 class="center" style="margin-bottom: 10px; margin-top: 10px;">
  <a href="<%= edit_section_path %>" class="btn-medium btn-floating waves-effect waves-light no-margin orange tooltipped" data-tooltip="Edit Section" data-delay="0" data-position="left"><i class="mdi-editor-border-color"></i></a>
</h5>
      <%end%>
</div>
<div class="valign-wrapper">

  <% if @sections.find_by(order: @section.order-1) %>
      <%= link_to @sections.find_by(order: @section.order-1), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-back valign"></i>
      <% end %>
  <% else %>
      <div class="btn btn-default disabled">
        <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-back valign"></i>
      </div>
  <% end %>

  <div class="container">
    <% if @section.contentType =="vid" %>
        <div class="video-container">
          <iframe width="854" height="510" src="<%=raw(@video)%>" frameborder="0" allowfullscreen></iframe>
        </div>
    <% end %>
  </div>

  <% if @sections.find_by(order: @section.order+1) %>
      <%= link_to @sections.find_by(order: @section.order+1), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-forward valign"></i>
      <% end %>
  <% else %>
      <%= link_to @quizzes.find_by(chapter_id: @section.chapter_id), class: "btn btn-default" do %>
          <i style="float:left vertical-align:middle" class="large mdi-navigation-arrow-forward valign"></i>
      <% end %>
  <% end %>
</div>
<div class="container">
  <h3 class="left-align"><a style="color:<%if passed?(@section.chapter)==1%> green"
  <% elsif passed?(@section.chapter)==0 %>red"
  <% else %>grey"
  <% end %>href="<%= polymorphic_path @section.chapter.course %>
  "><i class="mdi-navigation-chevron-left"> </i><%= @section.chapter.name %> </a></h3>
</div>