config/routes.rb
Rails.application.routes.draw do
  get 'quiz_results/new'

  get 'quizzes/new'

  get 'user_milestones/new'

  get 'sections/new'

  get 'chapters/new'

  get 'courses/new'

  get 'organizations/new'

  get 'sessions/new'

  resources :organizations
  resources :users
  resources :courses do
    post 'save'=> 'courses#save'
    get 'createTempChapter'=> 'chapters#createTempChapter'
  end

  resources :chapters do
    post 'save'=> 'chapters#save'
  end
  resources :sections do
    post 'saveVideo'=> 'sections#saveVideo'
  end
  resources :quizzes
  resources :quizzes do
    resources :quiz_results
  end

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'organizations#new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'addUsers' => 'organizations#newUsers'
  get 'editMode' => 'courses#editMode'
  get 'createTempCourse'=> 'courses#createTempCourse'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
  end

  def create
    @oldCourse = Course.find_by
    @course = Course.new(course_params)

  end

  def show
    @course = Course.find(params[:id])
    @chapters = @course.chapters
    @finishedChapters = getFinishedChapter(@course)
    if !@finishedChapters.nil?
      @currentChapters = @chapters-@finishedChapters
    else
      @currentChapters=@chapters
    end
    if (current_user.active_courses.find_by(course_id: @course.id).nil?)
      @active_course = ActiveCourse.new(user_id: current_user.id, course_id: @course.id, certification_complete: false)
      @active_course.save
    end
  end

  def createTempCourse
    newCourse = Course.create(name: "Create New Course", description: "Enter Description Here", imageSource: "NewCourse.png", default: false)

    current_user.organization.courses << newCourse
    redirect_to edit_course_path newCourse.id
  end

  def index
    @available_courses =current_user.organization.courses
    @active_courses = getActiveCourses
    @finished_courses = getFinishedCourses
    @available_courses-=getActiveCourses
    @active_courses -=@finished_courses
    @temp_course = Course.find_by(name: "Create New Course")
  end

  def editMode
    @available_courses =current_user.organization.courses
    @active_courses = getActiveCourses
    @available_courses-=getActiveCourses

  end

  def save
    @oldCourse = Course.find(params[:course_id])
    i=0
    current_user.organization.courses.each do |course|
      if course == @oldCourse
        break
      end
      i=i+1
    end
    if !@oldCourse.default

      @newCourse = Course.new(course_params)
      @newCourse.id = @oldCourse.id
      @newCourse.chapters = @oldCourse.chapters
      @newCourse.chapters.each do |chapter|
        chapter.sections = @oldCourse.chapters.find_by(id: chapter.id).sections
      end
      @newCourse.default=false
      if params[:course][:photo].nil?
        if @oldCourse.photo_file_name.nil?
          @newCourse.imageSource=@oldCourse.imageSource
        else
          @newCourse.photo = @oldCourse.photo
        end

      end

      current_user.organization.courses[i] = @newCourse
      Course.delete(@oldCourse.id)
      @newCourse.save

    end

    redirect_to courses_path
  end

  def edit
    @available_courses =current_user.organization.courses
    @active_courses = getActiveCourses
    @finished_courses = getFinishedCourses
    @available_courses-=getActiveCourses
    @active_courses -=@finished_courses
    @temp_course = Course.find_by(name: "Create New Course")
    @editCourse = Course.find_by id: params[:id]
    @course= Course.new
  end

  private

  def cloneCourse (course)
    newCourse = course.dup

    course.chapters.each do |chapter|
      newChapter= chapter.dup
      newChapter.course_id =newCourse.id
      newCourse.chapters << newChapter
      chapter.sections.each do |section|
        newSection = section.dup
        newSection.chapter_id = newChapter.id
        newSection.save
        newChapter.sections << newSection
      end
    end
    newCourse.save
    newCourse
  end


  def getActiveCourses
    @available_courses =current_user.organization.courses
    @active_courses = Array.new
    current_user.active_courses.each do |active_course|
      if !@available_courses.find_by(id: active_course.course_id).nil?
        @active_courses.push @available_courses.find_by(id: active_course.course_id)
      end
    end
    return @active_courses
  end

  def getFinishedCourses
    @finished_courses = Array.new
    current_user.active_courses.each do |active_course|
      if active_course.certification_complete
        @finished_courses.push Course.find(active_course.course_id)
      end
    end
    @finished_courses
  end

  def course_params
    params.require(:course).permit(:photo, :name, :description)
  end

  def getFinishedChapter course
    @finishedChapters = Array.new
    course.chapters.each do |chapter|
      if passed?(chapter)==1
        @finishedChapters.push chapter
      end
    end
    @finishedChapters
  end

  def passed? (chapter)
    if !chapter.quiz.nil? && !chapter.quiz.quiz_results.find_by(user_id: current_user.id).nil?
      if chapter.quiz.quiz_results.find_by(user_id: current_user.id, passed: false)
        return 0
      elsif chapter.quiz.quiz_results.find_by(user_id: current_user.id, passed: true)
        return 1
      end
    else
      return -1
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/views/courses/_chapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">

    <div class="card-content">
                            <span class="card-title activator orange-text text-darken-2"><%= chapter.name %>
                           </span>
      <p><%= chapter.overview %></p>
    </div>
    <div class="card-reveal">
      <span class="card-title orange-text text-darken-2">Sections<i class="mdi-navigation-close right"></i></span>
      <ol>
        <% chapter.sections.each do |section| %>
            <li> <%= link_to section.name, section %></li>
        <% end %>
        <% if !chapter.quiz.nil? %>
            <li> <%= link_to chapter.quiz.name, chapter.quiz %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/courses/_courseCard.html.erb
<div class="col s12 m4">
  <div class="card medium">

    <div class="card-image waves-effect waves-block waves-light">
      <% if course.imageSource.nil? %>
          <img class="activator" src=<%= asset_path course.photo.url %>>
      <% else %>
          <img class="activator" src=<%= asset_path course.imageSource %>>
      <% end %>
    </div>
    <div class="card-content">
      <span class="card-title activator orange-text text-darken-2"><%= course.name %></span>

    </div>
    <div class="card-reveal">
      <span class="card-title orange-text text-darken-2 activator"><%= course.name %>
        <i class="mdi-navigation-close right"></i></span>

      <p><%= course.description %></p>
      <%= link_to "Continue", course %>

    </div>
  </div>
</div>

app/views/courses/_createChapterCard.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">
      <%= form_tag chapter_save_path(chapter.id), :html => {:class => "chapter_edit_card"} do %>
          <div class="chapter-card-content card-content activator">
            <span class="card-title grey-text text-darken-4">
              <%= text_field_tag "chapter_name", value= chapter.name, class: "card-field" %>
            </span>
            <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
                <i class="mdi-content-save"></i>
            <% end %>
            <%= text_area_tag "chapter_overview", content=chapter.overview, class: "card-text-area materialize-textarea" %>
            <h2 class="activator no-margin"><i class="mdi-navigation-arrow-drop-down"></i></h2>
          </div>

          <div class="card-reveal">
          <span class="card-title orange-text text-darken-2">Sections
            <i class="mdi-navigation-close right"></i>
            <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
                <i class="mdi-content-save"></i>
            <% end %>
          </span>
          <ol>
            <% for i in 1..5 %>
                <li><%= text_field_tag "section"+i.to_s+"_name", value= section.name %></li>
            <% end %>

          </ol>
          </div>
      <% end %>

      </div>
</div>

app/views/courses/_disabledChapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small disabled">

    <div class="card-content">
      <span class="card-title activator orange-text text-darken-2"><a href="<%= course_createTempChapter_path params[:id] %>">Create New Chapter</a></span>

      <p>Enter Chapter Description</p>
    </div>

  </div>
</div>

app/views/courses/_editChapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">

    <div class="card-content">
       <span class="card-title activator orange-text text-darken-2"><%= chapter.name %></span>
      <% if !chapter.course.default && current_user.clearance>1%>
          <a href="<%= edit_chapter_path(chapter.id) %>" class="btn-medium btn-floating waves-effect waves-light no-margin orange right tooltipped" data-tooltip="Edit Chapter" data-delay="0"><i class="mdi-editor-border-color"></i></a>
      <% end %>
      <p><%= chapter.overview %></p>

    </div>

    <div class="card-reveal">
      <span class="card-title orange-text text-darken-2">Sections<i class="mdi-navigation-close right"></i></span>
      <ol>
        <% chapter.sections.each do |section| %>
            <li> <%= link_to section.name, section %></li>
        <% end %>

        <% if !chapter.quiz.nil? %>
            <li> <%= link_to chapter.quiz.name, chapter.quiz %></li>
        <% end %>
      </ol>
    </div>


  </div>
</div>

app/views/courses/_failChapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">
    <div class="progress no-margin">
      <div class="determinate" style="background-color:red">
      </div>
    </div>
    <div class="card-content">
                            <span class="card-title activator orange-text text-darken-2"><%= chapter.name %>
                           </span>
      <% if !chapter.course.default %>
          <a href="<%= edit_chapter_path(chapter.id) %>" class="btn-medium btn-floating waves-effect waves-light no-margin orange right"><i class="mdi-editor-border-color"></i></a>
      <% end %>
      <p><%= chapter.overview %></p>
    </div>
    <div class="card-reveal">
      <span class="card-title orange-text text-darken-2">Sections<i class="mdi-navigation-close right"></i></span>
      <ol>
        <% chapter.sections.each do |section| %>
            <li> <%= link_to section.name, section %></li>
        <% end %>
        <% if !chapter.quiz.nil? %>
            <li> <%= link_to chapter.quiz.name, chapter.quiz %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/courses/_modifyChapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">
      <%= form_tag chapter_save_path(chapter.id), :html => {:class => "chapter_edit_card"} do %>
          <div class="chapter-card-content card-content activator">
            <span class="card-title grey-text text-darken-4">
              <%= text_field_tag "chapter_name", value= chapter.name, class: "card-field" %>
            </span>
            <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
                <i class="mdi-content-save"></i>
            <% end %>
            <%= text_area_tag "chapter_overview", content=chapter.overview, class: "card-text-area materialize-textarea" %>
            <h2 class="activator no-margin"><i class="mdi-navigation-arrow-drop-down"></i></h2>
          </div>

          <div class="card-reveal">
          <span class="card-title orange-text text-darken-2">Sections
            <i class="mdi-navigation-close right"></i>
            <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
                <i class="mdi-content-save"></i>
            <% end %>
          </span>
          <ol>
            <% chapter.sections.each do |section| %>
                <li><%= text_field_tag "section"+section.id.to_s+"_name", value= section.name %></li>
            <% end %>
            <% if !chapter.quiz.nil? %>
                <li><%= text_field_tag "quiz_name", value= chapter.quiz.name %></li>
            <% end %>
          </ol>
          </div>
      <% end %>

      </div>
</div>

app/views/courses/_passChapterCard.html.erb
<div class="col s12 m6">
  <div class="card grey lighten-3 small">
    <div class="progress no-margin" >
      <div class="determinate" style="background-color:green">
      </div>
    </div>
    <div class="card-content">
                            <span class="card-title activator orange-text text-darken-2"><%= chapter.name %>
                              </span>
      <% if !chapter.course.default%>
          <a href="<%= edit_chapter_path(chapter.id)%>" class="btn-medium btn-floating waves-effect waves-light no-margin orange right"><i class="mdi-editor-border-color"></i></a>
      <%end%>
      <p><%= chapter.overview %></p>
    </div>
    <div class="card-reveal">
      <span class="card-title orange-text text-darken-2">Sections<i class="mdi-navigation-close right"></i></span>
      <ol>
        <% chapter.sections.each do |section| %>
            <li> <%= link_to section.name, section %></li>
        <% end %>
        <% if !chapter.quiz.nil? %>
            <li> <%= link_to chapter.quiz.name, chapter.quiz %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/courses/_saveCourseCard.html.erb
<div class="col s12 m4">
  <div class="card medium">
    <%= form_for @course,:url => course_save_path(course.id), :html => {:class => "chapter_edit_card"} do |form| %>
    <div class="card-image waves-effect waves-block waves-light valign-wrapper">
            <% if course.imageSource.nil? %>
          <img class="activator" style="position: absolute" src=<%= asset_path course.photo.url %>>
      <% else %>
          <img class="activator" style="position: absolute"src=<%= asset_path course.imageSource %>>
      <% end %>

    </div>


        <div class="card-content">
          <label class="cabinet valign">
            <%= form.file_field :photo %>
          </label>
          <span class="card-title" style="color:black">
            <%= form.text_field :name, :value => course.name,class:"card-field" %>

            <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
                    <i class="mdi-content-save"></i>
                <% end %>
          </span>

        </div>
        <div class="card-reveal">
           <span class="card-title orange-text text-darken-2"><%= course.name %>
             <i class="mdi-navigation-close right"></i>
           </span>
          <%= form.text_area :description, :value => course.description, class: "text-area" %>
          <%= button_tag(:class => "orange btn-medium btn-floating right") do %>
              <i class="mdi-content-save"></i>
          <% end %>
        </div>
    <% end %>

  </div>
</div>

app/views/courses/createChapter.html.erb
<div class="container">

  <% if !@active_courses.first.nil? %>
      <h2 style="margin-bottom:10px">Current Courses</h2>
  <% end %>

  <div class="row">
    <% @active_courses.each do |course| %>
        <% if @editCourse==course %>
            <%= render 'courses/createChapterCard', course:course %>
        <% else %>
            <%= render 'courses/courseCard', course: course %>
        <% end %>
    <% end %>
  </div>

  <% if !@available_courses.first.nil? %>
      <h2>Availaible Courses</h2>
  <% end %>

  <div class="row">
    <% @available_courses.each do |course| %>
    <% if @editCourse==course %>
        <%= render 'courses/createChapterCard', course:course %>
    <% else %>
        <%= render 'courses/courseCard', course: course %>
    <% end %>
        <%end%>
  </div>



</div>

app/views/courses/edit.html.erb
<div class="container">
  <ul class="collapsible" data-collapsible="expandable">


    <% if !@active_courses.first.nil? %>
        <li>
          <div class="collapsible-header active"><h3 class="center">Current Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @active_courses.each do |course| %>
                  <% if @editCourse==course %>
                      <%= render 'courses/saveCourseCard', course: course %>
                  <% else %>
                      <%= render 'courses/courseCard', course: course %>
                  <% end %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>


    <% if !@available_courses.first.nil? %>
        <li>
          <div class="collapsible-header active"><h3 class="center">Available Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @available_courses.each do |course| %>
                  <% if @editCourse==course %>
                      <%= render 'courses/saveCourseCard', course: course %>
                  <% else %>
                      <%= render 'courses/courseCard', course: course %>
                  <% end %>
              <% end %>

            </div>
          </div>
        </li>
    <% end %>
    <% if !@finished_courses.first.nil? %>
        <li>
          <div class="collapsible-header"><h3 class="center">Finished Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @finished_courses.each do |course| %>
                  <% if @editCourse==course %>
                      <%= render 'courses/saveCourseCard', course: course %>
                  <% else %>
                      <%= render 'courses/courseCard', course: course %>
                  <% end %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>

  </ul>

</div>

app/views/courses/index.html.erb
<div class="container">
  <ul class="collapsible" data-collapsible="expandable">


    <% if !@active_courses.first.nil? %>
        <li>
          <div class="collapsible-header active"><h3 class = "center">Current Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @active_courses.each do |course| %>
                  <%= render 'courses/editCourseCard', course: course %>
              <% end %>
              <% if current_user.clearance>1 && @available_courses.first.nil?%>
                  <%= render 'courses/disabledCourseCard' %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>


    <% if !@available_courses.first.nil? %>
        <li>
          <div class="collapsible-header active"><h3 class = "center">Available Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @available_courses.each do |course| %>
                  <%= render 'courses/editCourseCard', course: course %>
              <% end %>
              <% if current_user.clearance>1  %>
                  <%= render 'courses/disabledCourseCard' %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>
    <% if !@finished_courses.first.nil? %>
        <li>
          <div class="collapsible-header"><h3 class = "center">Finished Courses</h3></div>
          <div class="collapsible-body">
            <div class="row">
              <% @finished_courses.each do |course| %>
                  <%= render 'courses/editCourseCard', course: course %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>

  </ul>

</div>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<div class="container">

  <h2><%= @course.name %></h2>

  <ul class="collapsible" data-collapsible="expandable">
    <% if !@currentChapters.nil? %>
        <li>
          <div class="collapsible-header active"><h3 class="center">Current Chapters</h3></div>
          <div class="collapsible-body">
            <div class="row">

              <% @currentChapters.each do |chapter| %>
                  <% if passed?(chapter)==0 %>
                      <%= render 'courses/failChapterCard', chapter: chapter %>
                  <% elsif passed?(chapter)==-1 %>
                      <%= render 'courses/editChapterCard', chapter: chapter %>
                  <% end %>
              <% end %>
              <% if current_user.clearance>1 %>
                  <%= render 'courses/disabledChapterCard' %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>

    <% if !@finishedChapters.nil?  %>
        <li>
          <div class="collapsible-header"><h3 class="center">Finished Chapters</h3></div>
          <div class="collapsible-body">
            <div class="row">

              <% @finishedChapters.each do |chapter| %>
                  <%= render 'courses/passChapterCard', chapter: chapter %>
              <% end %>

              <% if current_user.clearance>1&& @currentChapters.nil? %>
                  <%= render 'courses/disabledChapterCard' %>
              <% end %>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>